// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAdKFkAFi1tTEwrSfd2M4xzghcZmdBjwE',
    appId: '1:91110791955:web:f0be038507e330444a58e6',
    messagingSenderId: '91110791955',
    projectId: 'flutter-project-7989d',
    authDomain: 'flutter-project-7989d.firebaseapp.com',
    storageBucket: 'flutter-project-7989d.firebasestorage.app',
    measurementId: 'G-WR2DECZ3EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRqv82Q3JyLE7PHWOt8JoKOVVOzbcKgjg',
    appId: '1:91110791955:android:d80641b403bf8f954a58e6',
    messagingSenderId: '91110791955',
    projectId: 'flutter-project-7989d',
    storageBucket: 'flutter-project-7989d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW5AzqS-tzCl9fnyGpSMq5gSQMmd0HJ9c',
    appId: '1:91110791955:ios:d34d003cc0af9e384a58e6',
    messagingSenderId: '91110791955',
    projectId: 'flutter-project-7989d',
    storageBucket: 'flutter-project-7989d.firebasestorage.app',
    iosBundleId: 'com.example.flutterUserAccountApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW5AzqS-tzCl9fnyGpSMq5gSQMmd0HJ9c',
    appId: '1:91110791955:ios:d34d003cc0af9e384a58e6',
    messagingSenderId: '91110791955',
    projectId: 'flutter-project-7989d',
    storageBucket: 'flutter-project-7989d.firebasestorage.app',
    iosBundleId: 'com.example.flutterUserAccountApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAdKFkAFi1tTEwrSfd2M4xzghcZmdBjwE',
    appId: '1:91110791955:web:0e94ed2a5101f7414a58e6',
    messagingSenderId: '91110791955',
    projectId: 'flutter-project-7989d',
    authDomain: 'flutter-project-7989d.firebaseapp.com',
    storageBucket: 'flutter-project-7989d.firebasestorage.app',
    measurementId: 'G-PEBV8K050X',
  );
}
